export {default as Article} from './artical/Article'
export {default as Brand} from './brand/Brand'
export {default as CallToAction} from './call-to-action/CallToAction'
export {default as Feature} from './feature/Feature'
export {default as Navbar} from './navbar/Navbar'
export {default as Background} from './background/Background'